export const FEACH_USER_REQUEST = 'FEACH_USER_REQUEST';
export const FEACH_USER_SUCCUSS = 'FEACH_USER_SUCCUSS';
export const FEACH_USER_FAILURE = 'FEACH_USER_FAILURE';
export const DELETE_USER = 'DELETE_USER';